PL_MVC/Controllers/AseguradoraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AseguradoraController : Controller
    {
        // GET: Aseguradora
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result result = BL.Aseguradora.GetAll();
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            if (result.Correct)
            {
                aseguradora.Aseguradoras = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(aseguradora);
        }

        [HttpGet]
        public ActionResult Form(int? IdAseguradora)
        {
            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();
            ML.Result resultusuario = BL.Usuario.GetAllEF(usuario);
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            aseguradora.Usuario = new ML.Usuario();

            aseguradora.Usuario = new ML.Usuario();
            if (IdAseguradora == null)
            {
                aseguradora.Usuario.Usuarios = resultusuario.Objects;
                return View(aseguradora);
            }
            else
            {
                ML.Result result = BL.Aseguradora.GetById(IdAseguradora.Value);
                if (result.Correct)
                {
                    aseguradora = (ML.Aseguradora)result.Objeto;
                    aseguradora.Usuario.Usuarios = resultusuario.Objects;
                    return View(aseguradora);
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar la aseguradora";
                }
                return View(aseguradora);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Aseguradora aseguradora)
        {
            //ADD
            if (aseguradora.IdAseguradora == 0)
            {
                ML.Result result = BL.Aseguradora.Add(aseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            //else
            {
                //UPDATE
                if (aseguradora != null)
                {
                    ML.Result result = BL.Aseguradora.Update(aseguradora);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                }
            }
            return PartialView("Modal");
        }

        //[HttpDelete]
        public ActionResult Delete(int idAseguradora)
        {
            ML.Aseguradora aseguradora = new ML.Aseguradora();
            if (aseguradora != null)
            {
                ML.Result result = BL.Aseguradora.Delete(idAseguradora);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                return Redirect("/Aseguradora/GetAll");
            }
            return PartialView("Modal");
        }
    }
}

PL_MVC/Views/Aseguradora/Form.cshtml
@model ML.Aseguradora
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>Form</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Aseguradora", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <h3 class="text-center">Datos de la aseguradora</h3>
                <div class="form-horizontal">
                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.HiddenFor(model => model.IdAseguradora)

                            @*@Html.TextBoxFor(model => model.IdUsuario, new { @class = "hidden form-control" })

                                @Html.ValidationMessageFor(model => model.IdUsuario)*@
                        </div>
                    </div>
                    <div class="container">
                        <div class="row">
                            <div class="col-md-6 col-md-offset-4">
                                <div class="form-group">

                                    @Html.LabelFor(model => model.Nombre)

                                    @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                                    @Html.ValidationMessageFor(model => model.Nombre)
                                </div>
                            </div>
                            <div class="col-md-6 col-md-offset-4">
                                <div class="form-group">

                                    @Html.LabelFor(model => model.Usuario)

                                    @Html.DropDownListFor(model => model.Usuario.IdUsuario, new SelectList(Model.Usuario.Usuarios, "IdUsuario", "NombreCompleto"), "Seleccione un usuario", new { @class = "form-control" })

                                    @Html.ValidationMessageFor(model => model.Usuario.IdUsuario)
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="container">
                        <div class="row">
                            <div class="col-md-3 col-md-offset-4">
                                <input type="submit" value="Guardar" class="btn btn-success" />

                                @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
                            </div>
                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

@section Scripts{

    <script src="~/lib/jquery/dist/jquery.js"></script>
    <script type="text/javascript">
        function readImage(imagen) {
            var fileName = imagen.value;
            var idxDot = fileName.lastIndexOf(".") + 1;
            var extFile = fileName.substr(idxDot, fileName.length).toLowerCase();

            if (extFile == "jpg" || extFile == "jpeg" || extFile == "png") {

                if (imagen.files && imagen.files[0]) {
                    var reader = new FileReader();
                    reader.onload = (e) => {
                        $("#ImagenPreview").attr("src", e.target.result);
                    };
                    reader.readAsDataURL(imagen.files[0]);
                }

            } else {

                alert("This is not an allowed file type. \nOnly jpg / jpeg and png files are allowed!.");

                $('#inputImage').val(null);

                $("#ImagenPreview").attr("src", "~/Image/sinlogo.jpg");

            }

        }
    </script>
}

PL_MVC/Views/Aseguradora/GetAll.cshtml
@model ML.Aseguradora
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Lista de Aseguradoras</h2>
    <p>Aqui puede ver, editar o agregar una aseguradora</p>
    <p>Para agregar una aseguradora presione el boton verde</p>
    <p>Para editar una aseguradora presione el boton azul</p>
    <p>Para eliminar una aseguradora presione el boton rojo</p>
    <hr />

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Aseguradora", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    <div class="row">
        <table class="table table-responsive" id="tblAseguradora">
            <thead class="table-dark">
                <tr>
                    <th>
                        IdAseguradora
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        FechaCreacion
                    </th>
                    <th>
                        FechaModificacion
                    </th>
                    <th>
                        NombreUsuario
                    </th>
                    <th>
                        Editar
                    </th>
                    <th>
                        Eliminar
                    </th>
                </tr>
            </thead>
            <tbody class="table-info">
                @foreach (ML.Aseguradora aseguradora in Model.Aseguradoras)
                {
                    <tr>
                        <td>
                            @aseguradora.IdAseguradora
                        </td>
                        <td>
                            @aseguradora.Nombre
                        </td>
                        <td>
                            @aseguradora.FechaCreacion
                        </td>
                        <td>
                            @aseguradora.FechaModificacion
                        </td>
                        <td>
                            @aseguradora.Usuario.Nombre @aseguradora.Usuario.ApellidoPaterno @aseguradora.Usuario.ApellidoMaterno
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary glyphicon glyphicon-edit" href="@Url.Action("Form", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })"></a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Aseguradora", new { IdAseguradora = aseguradora.IdAseguradora })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

@section Scripts
    {

    <script src="https://code.jquery.com/jquery-3.5.1.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.material.min.js"></script>
    <script src="https://cdn.datatables.net/1.13.1/js/dataTables.bootstrap5.min.js"></script>

    <script>
        $(document).ready(function () {
            $('#tblAseguradora').DataTable({
                searching: false,
                "lengthMenu": [[5, 10, 15, 20, -1], [5, 10, 15, 20, "All"]],
                autoWidth: false,
                columnDefs: [
                    {
                        targets: ['_all'],
                        className: 'mdc-data-table__cell',
                    },
                ],
                language: {
                    url: "//cdn.datatables.net/plug-ins/9dcbecd42ad/i18n/Spanish.json",
                },
            });
        });
    </script>

}

PL_MVC/Views/Aseguradora/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Aseguradora", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>