PL_MVC/Controllers/EmpresaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class EmpresaController : Controller
    {
        // GET: Empresa
        [HttpGet]
        public ActionResult GetAll(ML.Empresa empresa)
        {
            ML.Result result = BL.Empresa.GetAllEF(empresa);
            if (result.Correct)
            {
                empresa.Empresas = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(empresa);
        }

        [HttpGet]
        public ActionResult Form(int? IdEmpresa)
        {
            ML.Empresa empresa = new ML.Empresa();
            if (IdEmpresa == null)
            {
                return View();
            }
            else
            {
                ML.Result result = BL.Empresa.GetByIdEF(IdEmpresa.Value);
                if (result.Correct)
                {
                    empresa = (ML.Empresa)result.Objeto;
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar el usuario";
                }
                return View(empresa);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Empresa empresa)
        {
            HttpPostedFileBase file = Request.Files["ImagenData"];

            //if (file.ContentLength > 0)
            //{
            //    empresa.Logo = ConvertToBytes(file);
            //}
            //ADD
            if (empresa.IdEmpresa == 0)
            {
                ML.Result result = BL.Empresa.AddEF(empresa);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                //UPDATE
                if (empresa != null)
                {
                    ML.Result result = BL.Empresa.UpdateEF(empresa);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                }
            }
            return PartialView("Modal");
        }

        //[HttpDelete]
        public ActionResult Delete(ML.Empresa empresa)
        {
            if (empresa != null)
            {
                ML.Result result = BL.Empresa.DeleteEF(empresa);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                return Redirect("/Empresa/GetAll");
            }
            return PartialView("Modal");
        }

        public byte[] ConvertToBytes(HttpPostedFileBase logo)
        {
            byte[] data = null;
            System.IO.BinaryReader reader = new System.IO.BinaryReader(logo.InputStream);
            data = reader.ReadBytes((int)logo.ContentLength);
            return data;
        }
    }
}

PL_MVC/Controllers/UsuarioController.cs
using ML;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class UsuarioController : Controller
    {
        // GET: Usuario
        [HttpGet]
        public ActionResult GetAll()
        {
            ML.Result resultrol = BL.Rol.GetAllEF();
            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();
            ML.Result result = BL.Usuario.GetAllEF(usuario);
            if (result.Correct)
            {
                usuario.Rol.Roles = resultrol.Objects;
                usuario.Usuarios = result.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(usuario);
        }

        [HttpPost]
        public ActionResult GetAll(ML.Usuario usuario)
        {
            ML.Result resultrol = BL.Rol.GetAllEF();
            ML.Result result = BL.Usuario.GetAllEF(usuario);
            if (result.Correct)
            {
                usuario.Usuarios = result.Objects;
                usuario.Rol.Roles = resultrol.Objects;
            }
            else
            {
                ViewBag.Message = "Ocurrio un error al realizar la consulta";
            }
            return View(usuario);
        }

        public JsonResult GetEstado(int IdPais)
        {
            var result = BL.Estado.GetByIdPais(IdPais);

            return Json(result.Objects, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetMunicipio(int IdEstado)
        {
            var result = BL.Municipio.GetByIdEstado(IdEstado);

            return Json(result.Objects, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetColonia(int IdMunicipio)
        {
            var result = BL.Colonia.GetByIdMunicipio(IdMunicipio);

            return Json(result.Objects, JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Form(byte? IdUsuario)
        {
            ML.Result resultrol = BL.Rol.GetAllEF();
            ML.Usuario usuario = new ML.Usuario();
            usuario.Rol = new ML.Rol();

            ML.Result resultpais = BL.Pais.GetAll();
            usuario.Direccion = new ML.Direccion();
            usuario.Direccion.Colonia = new ML.Colonia();
            usuario.Direccion.Colonia.Municipio = new ML.Municipio();
            usuario.Direccion.Colonia.Municipio.Estado = new ML.Estado();
            usuario.Direccion.Colonia.Municipio.Estado.Pais = new ML.Pais();

            if (IdUsuario == null)
            {
                usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultpais.Objects;
                usuario.Rol.Roles = resultrol.Objects;
                
                return View(usuario);
            }
            else
            {
                ML.Result result = BL.Usuario.GetByIdEF(IdUsuario.Value);
                if (result.Correct)
                {
                    usuario = (ML.Usuario)result.Objeto;
                    usuario.Direccion.Colonia.Municipio.Estado.Pais.Paises = resultpais.Objects;

                    ML.Result resultEstado = BL.Estado.GetByIdPais(usuario.Direccion.Colonia.Municipio.Estado.Pais.IdPais);
                    usuario.Direccion.Colonia.Municipio.Estado.Estados = resultEstado.Objects;
                    ML.Result resultMunicipio = BL.Municipio.GetByIdEstado(usuario.Direccion.Colonia.Municipio.Estado.IdEstado);
                    usuario.Direccion.Colonia.Municipio.Municipios = resultMunicipio.Objects;
                    ML.Result resultColonia = BL.Colonia.GetByIdMunicipio(usuario.Direccion.Colonia.Municipio.IdMunicipio);
                    usuario.Direccion.Colonia.Colonias = resultColonia.Objects;

                    //usuario.Direccion.Colonia.Municipio.Estado.Estados = (List<object>)GetEstado(usuario.Direccion.Colonia.Municipio.Estado.Pais.IdPais).Data;
                    //usuario.Direccion.Colonia.Municipio.Municipios = (List<object>)GetMunicipio(usuario.Direccion.Colonia.Municipio.Estado.IdEstado).Data;
                    //usuario.Direccion.Colonia.Colonias = (List<object>)GetColonia(usuario.Direccion.Colonia.Municipio.IdMunicipio).Data;

                    usuario.Rol.Roles = resultrol.Objects;
                    return View(usuario);
                }
                else
                {
                    ViewBag.Message = "Ocurrio un error al buscar el usuario";
                }
                return View(usuario);
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Usuario usuario)
        {
            //IFormFile image = Request.Form.Files["FileImage"];
            //if (image != null)
            //{
            //    byte[] ImagenBytes = ConvertToBytes(image);
            //    usuario.Imagen = Convert.ToBase64String(ImagenBytes);
            //}
            //if(file.ContentLength>0)
            //{
            //    usuario.Imagen = ConvertToBytes(file);
            //}
            //ADD
            if (usuario.IdUsuario == 0)
            {
                ML.Result result = BL.Usuario.AddEF(usuario);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }
            else
            {
                //UPDATE
                if (usuario != null)
                {
                    ML.Result result = BL.Usuario.UpdateEF(usuario);
                    if (result.Correct)
                    {
                        ViewBag.Message = result.Message;
                    }
                    else
                    {
                        ViewBag.Message = "Error: " + result.Message;
                    }
                }
            }
            return PartialView("Modal");
        }

        //[HttpDelete]
        public ActionResult Delete(byte idUsuario)
        {
            ML.Usuario usuario = new ML.Usuario();
            if (usuario != null)
            {
                ML.Result result = BL.Usuario.DeleteEF(idUsuario);
                if (result.Correct)
                {
                    ViewBag.Message = result.Message;
                }
                else
                {
                    ViewBag.Message = "Error: " + result.Message;
                }
            }else
            {
                return Redirect("/Usuario/GetAll");
            }
            return PartialView("Modal");
        }

        //public static byte[] ConvertToBytes(IFormFile imagen)
        //{

        //    using var fileStream = imagen.OpenReadStream();

        //    byte[] bytes = new byte[fileStream.Length];
        //    fileStream.Read(bytes, 0, (int)fileStream.Length);

        //    return bytes;
        //}
        //public byte[] ConvertToBytes(HttpPostedFileBase imagen)
        //{
        //    byte[] data = null;
        //    System.IO.BinaryReader reader = new System.IO.BinaryReader(imagen.InputStream);
        //    data = reader.ReadBytes((int)imagen.ContentLength);
        //    return data;
        //}

        public JsonResult CambiarStatus(byte idUsuario, bool status)
        {
            var result = BL.Usuario.ChangeStatus(idUsuario, status);

            return Json(result.Objects);
        }
    }
}

PL_MVC/Views/Empresa/Form.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container-fluid">
    <h2>Form</h2>
    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Empresa", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">

                    <div class="form-group">

                        <div class="col-md-3">

                            @Html.LabelFor(model => model.IdEmpresa, new { @class = "hidden" })

                            @Html.TextBoxFor(model => model.IdEmpresa, new { @class = "hidden form-control" })

                            @Html.ValidationMessageFor(model => model.IdEmpresa)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Nombre)

                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control", @id = "txtNombre" })

                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Telefono)

                            @Html.TextBoxFor(model => model.Telefono, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Telefono)

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">

                            @Html.LabelFor(model => model.Email)

                            @Html.TextBoxFor(model => model.Email, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.Email)

                        </div>
                    </div>

                    <div class="form-group">
                        <div class="col-md-3">

                            @Html.LabelFor(model => model.DireccionWeb)

                            @Html.TextBoxFor(model => model.DireccionWeb, new { @class = "form-control" })

                            @Html.ValidationMessageFor(model => model.DireccionWeb)

                        </div>
                    </div>

                    @*<div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Logo)
                            <input type="file" name="ImagenData" onchange="readURL(this);" />
                            @if (Model.Logo != null)
                            {
                                <img id="ImagenPreview" src="data:image;base64,@Convert.ToBase64String(Model.Logo)" height="150" width="150">
                            }
                            else
                            {
                                <img id="ImagenPreview" src="~/Image/sinlogo.jpg" style="height:150px; width:150px;">
                            }
                            @Html.ValidationMessageFor(model => model.Logo)
                        </div>
                    </div>*@

                    @Html.HiddenFor(model => model.Logo)

                    <div class="form-group">
                        <div class="col-md-3">

                            <input type="submit" value="Guardar" class="btn btn-success" />

                            @Html.ActionLink("Regresar", "GetAll", "Empresa", htmlAttributes: new { @class = "btn btn-danger" })

                        </div>
                    </div>

                </div>
            }
        </div>
    </div>
</div>

@Scripts.Render("~/bundles/jquery")
<script type="text/javascript">
    function readURL(input)
    {
        if (input.files && input.files[0])
        {
            var reader = new FileReader();
            reader.onload = function (e)
            {
                $('#ImagenPreview').attr('src', e.target.result);
            };
            reader.readAsDataURL(input.files[0]);
        }
    }
</script>

PL_MVC/Views/Empresa/GetAll.cshtml
@model ML.Empresa
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h2>Lista de empresas</h2>
    <p>Aqui puede ver, editar o agrgar a una empresa</p>
    <p>Para agregar una empresa presione el boton verde</p>
    <p>Para editar una empresa presione el boton azul</p>
    <p>Para eliminar una empresa presione el boton rojo</p>

    <div class="row">
        <div style="float:right">
            @Html.ActionLink("+", "Form", "Empresa", htmlAttributes: new { @class = "btn btn-success" })
        </div>
    </div>

    <div class="row">
        <table class="table table-responsive">
            <thead>
                <tr>
                    <th>
                        IdEmpresa
                    </th>
                    <th>
                        Nombre
                    </th>
                    <th>
                        Telefono
                    </th>
                    <th>
                        Email
                    </th>
                    <th>
                        DireccionWeb
                    </th>
                    <th>
                        Imagen
                    </th>
                    <th>
                        Editar
                    </th>
                    <th>
                        Actualizar
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Empresa empresa in Model.Empresas)
                {
                    <tr>
                        <td>
                            @empresa.IdEmpresa
                        </td>
                        <td>
                            @empresa.Nombre
                        </td>
                        <td>
                            @empresa.Telefono
                        </td>
                        <td>
                            @empresa.Email
                        </td>
                        <td>
                            @empresa.DireccionWeb
                        </td>
                        <td>
                            @if (empresa.Logo != null)
                            {
                                <img src="data:image;base64,@Convert.ToBase64String(empresa.Logo)" style="height:150px; width:150px;" />
                            }
                            else
                            {
                                <img src="~/Image/sinlogo.jpg" style="height:150px; width:150px;" />
                            }
                        </td>
                        <td class="text-center">
                            <a class="btn btn-primary glyphicon glyphicon-edit" href="@Url.Action("Form", "Empresa", new { IdEmpresa = empresa.IdEmpresa })"></a>
                        </td>
                        <td class="text-center">
                            <a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Empresa", new { IdEmpresa = empresa.IdEmpresa })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Empresa/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">

                @Html.ActionLink("Regresar", "GetAll", "Usuario", htmlAttributes: new { @class = "btn btn-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>